#!/usr/bin/env python3
# Copyright (c) 2026 Amal Dev Haridevan
# SPDX-License-Identifier: MIT

"""Generate and optionally build stage-aware C++/Python acados wrappers."""

import argparse
import os
from pathlib import Path
import re
import shlex
import shutil
import subprocess
from typing import Union

from jinja2 import Environment, FileSystemLoader, StrictUndefined

TEMPLATES = (
    "model_ocp.cc.j2",
    "model_ocp.hh.j2",
    "model_ocp_py.cc.j2",
    "model_sim.cc.j2",
    "model_sim.hh.j2",
    "model_sim_py.cc.j2",
)

CMAKE_PROJECT_MARKER = "# Generated by AcadosCpp; do not edit this file."
VECTOR_TYPES = ("stl", "eigen")


def _validate_model_name(model_name: str) -> None:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", model_name):
        raise ValueError(
            "model_name must be a C identifier (letters, digits, and underscores)"
        )


def _validate_vector_type(vector_type: str) -> None:
    if vector_type not in VECTOR_TYPES:
        choices = ", ".join(VECTOR_TYPES)
        raise ValueError(f"vector_type must be one of: {choices}")


def _copy_generated_code(source: Path, destination: Path) -> None:
    """Copy the complete export, including model-specific constraint directories."""
    if source.resolve() == destination.resolve():
        return
    destination.mkdir(parents=True, exist_ok=True)
    for item in source.iterdir():
        # An acados CMake build tree contains an absolute source path in its
        # cache and cannot be reused after the export is copied elsewhere.
        if item.is_dir() and (
            item.name == "build" or item.name.startswith("cmake-build-")
        ):
            continue
        target = destination / item.name
        if item.is_dir():
            shutil.copytree(item, target, dirs_exist_ok=True)
        else:
            shutil.copy2(item, target)


def _write_cmake_project(
    destination: Path,
    model_name: str,
    vector_type: str,
    environment: Environment,
) -> None:
    """Wrap the acados-generated CMake project with the AcadosCpp targets."""
    cmake_path = destination / "CMakeLists.txt"
    acados_cmake_path = destination / "acados_generated.cmake"
    if not cmake_path.is_file():
        raise ValueError(f"Incomplete acados export; missing: {cmake_path}")

    current_cmake = cmake_path.read_text(encoding="utf-8")
    if current_cmake.startswith(CMAKE_PROJECT_MARKER):
        if not acados_cmake_path.is_file():
            raise ValueError(
                "AcadosCpp CMake project is missing acados_generated.cmake"
            )
    else:
        # Preserve the source list rendered by acados. It accounts for the
        # selected integrator, costs, constraints, and external functions.
        acados_cmake_path.write_text(current_cmake, encoding="utf-8")

    rendered = environment.get_template("CMakeLists.txt.j2").render(
        model_name=model_name,
        project_marker=CMAKE_PROJECT_MARKER,
        vector_type=vector_type,
    )
    cmake_path.write_text(rendered, encoding="utf-8")


def generate_code(
    model_name: str,
    c_generated_code_dir: str,
    output_dir: str,
    build_generated: bool = True,
    vector_type: str = "stl",
) -> None:
    """Create wrappers around an existing acados code export.

    Set ``build_generated=False`` to render/copy only, which is useful for
    cross-compilation and build-system integration. ``vector_type`` selects
    ``std::vector<double>`` (``"stl"``) or ``Eigen::VectorXd`` (``"eigen"``).
    """
    _validate_model_name(model_name)
    _validate_vector_type(vector_type)
    source = Path(c_generated_code_dir).expanduser().resolve()
    destination = Path(output_dir).expanduser().resolve()
    if not source.is_dir():
        raise ValueError(f"Generated code directory does not exist: {source}")
    if source != destination:
        common = Path(os.path.commonpath((source, destination)))
        if common == source or common == destination:
            raise ValueError(
                "Input and output directories must not contain one another"
            )

    required = (
        source / f"acados_solver_{model_name}.c",
        source / f"acados_solver_{model_name}.h",
        source / f"acados_sim_solver_{model_name}.c",
        source / f"acados_sim_solver_{model_name}.h",
        source / "CMakeLists.txt",
    )
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise ValueError("Incomplete acados export; missing: " + ", ".join(missing))

    _copy_generated_code(source, destination)
    environment = Environment(
        loader=FileSystemLoader(Path(__file__).resolve().parent / "templates"),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
    )
    _write_cmake_project(destination, model_name, vector_type, environment)
    for template_name in TEMPLATES:
        output_name = template_name.removesuffix(".j2")
        rendered = environment.get_template(template_name).render(
            model_name=model_name,
            vector_type=vector_type,
        )
        (destination / output_name).write_text(rendered, encoding="utf-8")

    print(f"Generated wrappers for '{model_name}' in '{destination}'")
    if build_generated:
        build(model_name, destination)


def _run(command: list[str], cwd: Path) -> None:
    print("+", shlex.join(command))
    subprocess.run(command, cwd=cwd, check=True)


def build(model_name: str, destination: Union[str, Path]) -> None:
    """Configure, build, and install the generated CMake project."""
    _validate_model_name(model_name)
    destination = Path(destination).resolve()
    if not destination.is_dir():
        raise ValueError(f"Destination does not exist: {destination}")

    acados_root_value = os.environ.get("ACADOS_ROOT")
    if not acados_root_value:
        raise EnvironmentError("ACADOS_ROOT environment variable is not set")
    acados_root = Path(acados_root_value).resolve()
    build_dir = destination / "build"
    _run(
        [
            "cmake",
            "-S",
            str(destination),
            "-B",
            str(build_dir),
            "-DCMAKE_BUILD_TYPE=Release",
            f"-DCMAKE_INSTALL_PREFIX={destination}",
            "-DACADOS_CPP_BUILD_PYTHON=ON",
            f"-DACADOS_INCLUDE_PATH={acados_root / 'include'}",
            f"-DACADOS_LIB_PATH={acados_root / 'lib'}",
        ],
        destination,
    )
    _run(["cmake", "--build", str(build_dir), "--parallel"], destination)
    _run(["cmake", "--install", str(build_dir)], destination)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate C++ and Python wrappers from acados-generated C code"
    )
    parser.add_argument("--model_name", required=True)
    parser.add_argument("--c_generated_code_dir", required=True)
    parser.add_argument("--output_dir", required=True)
    parser.add_argument(
        "--no-build", action="store_true", help="render wrappers without compiling"
    )
    parser.add_argument(
        "--vector_type",
        "--vector-type",
        choices=VECTOR_TYPES,
        default="stl",
        help="C++ vector representation (default: stl)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    generate_code(
        args.model_name,
        args.c_generated_code_dir,
        args.output_dir,
        build_generated=not args.no_build,
        vector_type=args.vector_type,
    )
